# Generated by Django 6.1 on 2026-08-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='exam_center',
            field=models.CharField(default='Online Examination Center - Center A', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='exam_date',
            field=models.CharField(default='15 September 2026, 10:00 AM', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.CharField(choices=[('GEN', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('EWS', 'Economically Weaker Section')], max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='obtained_marks',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(upload_to='candidates/photos/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='qualification_class',
            field=models.CharField(max_length=50, verbose_name='Class / Degree'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='signature',
            field=models.ImageField(upload_to='candidates/signatures/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
