# Generated by Django 6.1 on 2026-08-24 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_candidate_exam_center_candidate_exam_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_code', models.CharField(max_length=20, unique=True)),
                ('center_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('full_address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='razorpay_order_id',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.CharField(choices=[('UR', 'General / Unreserved'), ('OBC', 'Other Backward Class (OBC)'), ('SC', 'Scheduled Caste (SC)'), ('ST', 'Scheduled Tribe (ST)'), ('EWS', 'Economically Weaker Section (EWS)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exam_center',
            field=models.CharField(default='Center to be allotted', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exam_date',
            field=models.CharField(default='15 October 2026', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='qualification_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='registration_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='signature',
            field=models.ImageField(upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='center_choice_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref_1', to='portal.examcenter'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='center_choice_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref_2', to='portal.examcenter'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='center_choice_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref_3', to='portal.examcenter'),
        ),
    ]
