# Generated by Django 6.1 on 2026-08-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_examcenter_remove_candidate_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='aadhaar_doc',
            field=models.FileField(blank=True, null=True, upload_to='aadhaar_docs/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
