# Generated by Django 6.1 on 2026-08-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Other', 'Other')], default='Indian', max_length=20),
        ),
    ]
