# Generated by Django 6.1 on 2026-08-25 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_candidate_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate Application', 'verbose_name_plural': 'Candidate Applications'},
        ),
        migrations.AlterModelOptions(
            name='examcenter',
            options={'verbose_name': 'Exam Center', 'verbose_name_plural': 'Exam Centers'},
        ),
        migrations.AlterModelOptions(
            name='grievance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Grievance Ticket', 'verbose_name_plural': 'Grievance Tickets'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='center_choice_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref_1', to='portal.examcenter'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='center_choice_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref_2', to='portal.examcenter'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='center_choice_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref_3', to='portal.examcenter'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='registration_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='roll_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
