# Generated by Django 6.1 on 2026-08-26 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_candidate_options_alter_examcenter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='allotted_center',
            field=models.ForeignKey(blank=True, help_text='Exam center finalized by Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotted_candidates', to='portal.examcenter'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='exam_shift',
            field=models.CharField(default='Shift 1 (09:00 AM - 12:00 PM)', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_admit_card_released',
            field=models.BooleanField(default=False, verbose_name='Admit Card Released'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exam_center',
            field=models.CharField(blank=True, default='Center to be allotted', max_length=255, null=True),
        ),
    ]
