# Generated by Django 6.1 on 2026-08-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_candidate_allotted_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcenter',
            name='capacity_per_shift',
            field=models.PositiveIntegerField(default=100, help_text='Max candidates per shift'),
        ),
    ]
