# Generated by Django 6.1 on 2026-08-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_examcenter_capacity_per_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='entry_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entry Timestamp'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_present',
            field=models.BooleanField(default=False, verbose_name='Attended / Present'),
        ),
    ]
