# Generated by Django 6.1 on 2026-08-26 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_candidate_entry_verified_at_candidate_is_present'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(default='Central Examination Authority 2026', max_length=255)),
                ('exam_title', models.CharField(default='Combined Entrance Examination (CEE-2026)', max_length=255)),
                ('helpline_email', models.EmailField(default='support@examauthority.gov.in', max_length=254)),
                ('helpline_phone', models.CharField(default='+91-1800-2026-99', max_length=20)),
                ('announcement_ticker', models.TextField(default='Official Notice: Exam center allotment active. Admit cards available on candidate login.', help_text='Top scrolling news ticker on portal')),
                ('is_result_published', models.BooleanField(default=False, verbose_name='Publish Result Publicly on Portal')),
                ('result_published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Global Portal Setting',
                'verbose_name_plural': 'Global Portal Settings',
            },
        ),
        migrations.CreateModel(
            name='PresentCandidateResult',
            fields=[
            ],
            options={
                'verbose_name': '🎯 Result Entry (Present Candidates Only)',
                'verbose_name_plural': '🎯 Result Entry (Present Candidates Only)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.candidate',),
        ),
        migrations.AddField(
            model_name='candidate',
            name='exam_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Exam Marks (CBT)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='exam_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score %'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='exam_qualification_status',
            field=models.CharField(choices=[('QUALIFIED', 'Qualified'), ('NOT_QUALIFIED', 'Not Qualified'), ('PENDING', 'Pending Evaluation')], default='PENDING', max_length=20, verbose_name='Result Status'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='exam_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='All India Rank'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='exam_total_marks',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=6, verbose_name='Total Marks (CBT)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_result_declared',
            field=models.BooleanField(default=False, verbose_name='Individual Result Declared'),
        ),
        migrations.AddField(
            model_name='examcenter',
            name='assigned_incharge',
            field=models.ForeignKey(blank=True, help_text='Staff user assigned as Center Incharge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_center', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='allotted_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotted_candidates', to='portal.examcenter', verbose_name='Allotted Center'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.CharField(choices=[('PAYMENT', 'Payment / Fee Related'), ('DOCUMENT', 'Photo / Signature Correction'), ('ADMIT_CARD', 'Admit Card Issue'), ('CENTER', 'Exam Center Query'), ('RESULT', 'Result / Scorecard Query'), ('OTHER', 'Other Technical Issue')], max_length=20),
        ),
    ]
