# Generated by Django 6.1 on 2026-08-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_portalsetting_presentcandidateresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(db_index=True)),
                ('question_text', models.TextField(help_text='Question statement / problem description')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2)),
                ('exam_shift', models.CharField(choices=[('Shift 1', 'Shift 1 (Morning)'), ('Shift 2', 'Shift 2 (Evening)')], default='Shift 1', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Provisional Answer Key Item',
                'verbose_name_plural': 'Provisional Answer Key Items',
                'ordering': ['question_number'],
                'unique_together': {('question_number', 'exam_shift')},
            },
        ),
        migrations.CreateModel(
            name='QuestionObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2)),
                ('justification', models.TextField(help_text='Detailed justification / book reference')),
                ('supporting_doc', models.FileField(blank=True, null=True, upload_to='objections_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Under Review'), ('ACCEPTED', 'Accepted & Revised'), ('REJECTED', 'Rejected / Invalid')], default='PENDING', max_length=20)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='portal.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_objections', to='portal.answerkey')),
            ],
            options={
                'verbose_name': 'Candidate Objection / Challenge',
                'verbose_name_plural': 'Candidate Objections / Challenges',
                'ordering': ['-created_at'],
            },
        ),
    ]
