# Generated by Django 6.1 on 2026-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_answerkey_options_answerkey_is_revised_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=150)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email Dispatch'), ('SMS', 'SMS Gateway')], default='EMAIL', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Successfully Sent'), ('FAILED', 'Dispatch Failed')], default='SENT', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification Log (Email/SMS)',
                'verbose_name_plural': 'Notification Logs (Email/SMS)',
                'ordering': ['-sent_at'],
            },
        ),
    ]
