# Generated by Django 6.1 on 2026-08-24 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_candidate_aadhaar_doc_candidate_aadhaar_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('registration_no', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('PAYMENT', 'Payment / Fee Related'), ('DOCUMENT', 'Photo / Signature Correction'), ('ADMIT_CARD', 'Admit Card Issue'), ('CENTER', 'Exam Center Query'), ('OTHER', 'Other Technical Issue')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open / Under Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='portal.candidate')),
            ],
        ),
    ]
