# Generated by Django 6.1 on 2026-08-26 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_candidate_allotted_center_candidate_exam_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='allotted_center',
            field=models.ForeignKey(blank=True, help_text='Exam center finalized by Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotted_candidates', to='portal.examcenter', verbose_name='Allotted Center'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exam_date',
            field=models.CharField(choices=[('15 October 2026', '15 October 2026 (Day 1)'), ('16 October 2026', '16 October 2026 (Day 2)'), ('17 October 2026', '17 October 2026 (Day 3)'), ('18 October 2026', '18 October 2026 (Day 4)'), ('19 October 2026', '19 October 2026 (Day 5)')], default='15 October 2026', max_length=50, verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exam_shift',
            field=models.CharField(choices=[('Shift 1 (08:30 AM - 11:30 AM)', 'Shift 1: Morning (08:30 AM - 11:30 AM)'), ('Shift 2 (12:30 PM - 03:30 PM)', 'Shift 2: Afternoon (12:30 PM - 03:30 PM)'), ('Shift 3 (04:30 PM - 07:30 PM)', 'Shift 3: Evening (04:30 PM - 07:30 PM)')], default='Shift 1 (08:30 AM - 11:30 AM)', max_length=60, verbose_name='Exam Shift'),
        ),
    ]
