# Generated by Django 6.1 on 2026-08-26 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_answerkey_questionobjection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerkey',
            options={'ordering': ['question_number'], 'verbose_name': 'Provisional & Revised Answer Key', 'verbose_name_plural': 'Provisional & Revised Answer Keys'},
        ),
        migrations.AddField(
            model_name='answerkey',
            name='is_revised',
            field=models.BooleanField(default=False, help_text='True if modified after objection review'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Direct official resolution sent to student', null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ATTENDANCE_CHECKIN', 'Gate Attendance Check-in'), ('MARKS_ENTERED', 'CBT Marks Entry/Update'), ('RESULT_DECLARED', 'Result Published'), ('ADMIT_CARD_RELEASED', 'Admit Card Released'), ('KEY_REVISED', 'Answer Key Revised via Objection'), ('HELPDESK_RESOLVED', 'Helpdesk Query Resolved')], max_length=50)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.candidate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security & Audit Log',
                'verbose_name_plural': 'Security & Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
